Repository neo4j/docs-spark, pull requests merged in 2023-09, with the labels that each got.

#11 Update version and path
  antora.yml
  preview.yml
  publish.yml
Labels: cherry-pick to 5.x

#12 Update docs path
  antora.yml
  preview.yml
  publish.yml
Labels: 4.2

#14 Update version and mark new features
  antora.yml
  modules/ROOT/pages/configuration.adoc
  modules/ROOT/pages/gds.adoc
  modules/ROOT/pages/playground.adoc
  modules/ROOT/pages/reading.adoc
  preview.yml
  publish.yml
Labels: cherry-pick to 5.x

#15 add edit this page links (#13)
  preview.yml
  publish.yml
Labels: cherry-picked, 5.x
